### ISSUE TITLE
请教大佬如何构建数据集

### ISSUE THREAD

**Issue by xxg98** [SmartFlowAI/EmoLLM#126]
非常想知道写什么样的prompt可以来让GLM4、文心一言或者chatgpt4来构建数据集，因为特别想在其他领域也微调一个出来，大佬能指点一下嘛？

**Comment by aJupyter** [comment]
仓库里有

**Comment by aJupyter** [comment]
https://github.com/SmartFlowAI/EmoLLM/tree/main/datasets

**Comment by xxg98** [comment]
> https://github.com/SmartFlowAI/EmoLLM/tree/main/datasets


感谢感谢

**Comment by Franklinlifangcheng** [comment]
> 非常想知道写什么样的prompt可以来让GLM4、文心一言或者chatgpt4来构建数据集，因为特别想在其他领域也微调一个出来，大佬能指点一下嘛？

请问您研究的怎么样啦可以交流一下吗我最近也在尝试这个
