### ISSUE TITLE
评测数据请教

### ISSUE THREAD

**Issue by knifedone** [SmartFlowAI/EmoLLM#151]
您好，我有两个问题请教：
1. 通用评测： 通用评测的数据集来源是哪呀？
2. 专业评测： 这篇文章以及对应的数据集我没有找到，请问一下这篇文章是改名字了么？ 我要如何获取到对应的文章和数据集呢。CPsyCoun: A Report-based Multi-turn Dialogue Reconstruction and Evaluation Framework for Chinese Psychological Counseling

**Comment by aJupyter** [comment]
感谢关注 后续会补充细节

**Comment by techrex** [comment]
是不是这个作者的论文
https://ming-zch.github.io/
