### ISSUE TITLE
如何部署该模型到onnx，我正在试图将其部署为tensorRT格式。

### ISSUE THREAD

**Issue by MaShuo-dzu** [SmartFlowAI/EmoLLM#17]
ValueError: Trying to export a internlm model, that is a custom or unsupported architecture for the task feature-extraction, but no custom onnx configuration was passed as `custom_onnx_configs
`. Please refer to https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models for an example on how to export custom models. Pl
ease open an issue at https://github.com/huggingface/optimum/issues if you would like the model type internlm to be supported natively in the ONNX export.
我使用huggingface生态的onnx导出工具但是失败了，疑似不在huggingface onnx模型导出父类的一个选择范围？

**Comment by aJupyter** [comment]
可以提供一下详细的代码
