### ISSUE TITLE
关于微调

### ISSUE THREAD

**Issue by RyanOvO** [SmartFlowAI/EmoLLM#197]
在微调的文档中，有三个问题：
1. 微调数据集的地址默认是指py文件中的data_path参数值么？
2. 微调数据集的格式是否参照datasets中的数据集格式即可？譬如单论对话、多轮对话。
3. 基于ChatGLM3的微调，是否只能基于   基于Transformers的微调  文档来做？不能基于xtuner文档来做？

**Comment by aJupyter** [comment]
感谢关注
1. 是的
2. 是的
3. 可以基于xtuner 前者只是为了更好的让大家理解
可以参考：https://github.com/SmartFlowAI/EmoLLM/blob/main/xtuner_config/chatglm3_6b_lora_alpaca_e3.py
