### ISSUE TITLE
是否考虑支持最新的qwen系列模型？

### ISSUE THREAD

**Issue by RyanOvO** [SmartFlowAI/EmoLLM#244]
是否考虑支持最新的qwen系列模型？如，qwen 2 or 2.5

**Comment by aJupyter** [comment]
您好 感谢您对项目的关注
目前qwen支持这两个
- qwen https://github.com/SmartFlowAI/EmoLLM/blob/main/xtuner_config/qwen_7b_chat_qlora_e3.py
- qwen1.5 https://github.com/SmartFlowAI/EmoLLM?tab=readme-ov-file

qwen2和qwen2.5 并没有开源吧 后续如果开源会跟进
