### ISSUE TITLE
您好请问下CPsyCoun这篇论文在哪里？

### ISSUE THREAD

**Issue by threethreeLiu** [SmartFlowAI/EmoLLM#246]
您好，发现您测评模型中使用的《CPsyCoun: A Report-based Multi-turn Dialogue Reconstruction and Evaluation Framework for Chinese Psychological Counseling》这篇论文，我找了很多地方没找到这篇论文，能否提供下这篇论文吗？

**Comment by MING-ZCH** [comment]
hi~欢迎关注！我是CPsyCoun的作者
论文目前已中稿2024ACL会议，预计本周将会release论文和对应GitHub repo！
感谢您的关注

**Comment by lts0131** [comment]
> hi~欢迎关注！我是 CPsyCoun 的作者 论文目前已发表中稿 2024ACL 会议，**预计本周将发布论文并回复 GitHub 存储库**！ 感谢您的关注！

好的，我也在做相关的研究，想拿您的这篇作为引用，期待您发表

**Comment by MING-ZCH** [comment]
hi~CPsyCoun论文已发布，欢迎关注star！
论文：https://arxiv.org/abs/2405.16433
GitHub repo：https://github.com/CAS-SIAT-XinHai/CPsyCoun
