### ISSUE TITLE
增量预训练的merge数据有样例吗，dataset里的数据应该只能做指令微调

### ISSUE THREAD

**Issue by lcyuanjiang** [SmartFlowAI/EmoLLM#257]

**Comment by aJupyter** [comment]
请参考 https://github.com/SmartFlowAI/EmoLLM/blob/main/xtuner_config/pt/README.md

**Comment by aJupyter** [comment]
预训练的数据格式可以是任意的文本，这里只是举例

**Comment by aJupyter** [comment]
预训练的数据格式可以是任意的文本，这里只是举例
