### ISSUE TITLE
【GLM4-9B-chat Lora 微调 】文档的疑问

### ISSUE THREAD

**Issue by RyanOvO** [SmartFlowAI/EmoLLM#259]
[GLM4-9B-chat Lora 微调 文档](https://github.com/SmartFlowAI/EmoLLM/blob/main/doc/GLM-4-9B-chat%20Lora%20%E5%BE%AE%E8%B0%83%EF%BC%88llama-factory%EF%BC%89.md)
一文，其逻辑是，基于LlaMa-Factory微调框架，以GLM4为基座模型，数据集为EmoLLM的数据集，微调训练一个新的 EmoLLM-glm-4-9b-chat 模型  吗？

**Comment by aJupyter** [comment]
是的
