### ISSUE TITLE
部署运行EmoLLM服务时，打开界面一直please wait，显存和内存也没有被占用

### ISSUE THREAD

**Issue by wstsr333** [SmartFlowAI/EmoLLM#260]
![微信图片_20240709154409](https://github.com/SmartFlowAI/EmoLLM/assets/169221662/1afa08bf-a118-4fae-8585-6456e4af1c7e)
部署运行EmoLLM服务时，打开界面一直please wait，显存和内存也没有被占用

**Comment by aJupyter** [comment]
麻烦提供一下详细信息

**Comment by wstsr333** [comment]
![image](https://github.com/SmartFlowAI/EmoLLM/assets/169221662/860a5361-6431-4f6f-a6d4-f928bcceec5a)

**Comment by aJupyter** [comment]
你得点进去

**Comment by wstsr333** [comment]
我进去了

**Comment by wstsr333** [comment]
![image](https://github.com/SmartFlowAI/EmoLLM/assets/169221662/43ef44d1-175a-422c-83e2-f0c3cb20372f)

**Comment by wstsr333** [comment]
我是在autodl上面部署的

**Comment by wstsr333** [comment]
模型我已经自己下载下来放到model目录下了

**Comment by wstsr333** [comment]
还是please wait

**Comment by aJupyter** [comment]
你可以选择先把模型下载下来 再进行推理

**Comment by wstsr333** [comment]
我在autodl上面打开之后他不会有下一部动作，可能是服务器链接的问题吧，其他服务器没有遇到

**Comment by wstsr333** [comment]
对了，模型有开放api服务吗

**Comment by MING-ZCH** [comment]
> 对了，模型有开放api服务吗

暂时还未开放，已列入计划
