### ISSUE TITLE
Awesome project - Love to try it.

### ISSUE THREAD

**Issue by 99bits** [SmartFlowAI/EmoLLM#262]
Thank you for sharing this amazing project,

When i tried to "Experience the EmoLLM". I get this error.
Do you know what could be the problem.

<img width="697" alt="Screenshot 2024-07-09 at 23 49 06" src="https://github.com/SmartFlowAI/EmoLLM/assets/22409112/aa02d958-3fe9-4780-8658-79ebc588cc81">

**Comment by aJupyter** [comment]
https://openxlab.org.cn/apps/detail/ajupyter/EmoLLM-aiwei

hello，you can try this link.
