### ISSUE TITLE
readme页面的章节点击无法跳转

### ISSUE THREAD

**Issue by xxg98** [SmartFlowAI/EmoLLM#39]
看看我发现了什么hh，这个仓库真不错。
readme页面的文件目录、数据构建、微调指南等均无法跳转

**Comment by aJupyter** [comment]
欢迎关注EmoLLM项目。需要点击查看更多详情的，后面会考虑更新一下。

**Comment by xxg98** [comment]
> 需要点击查看更多详情的，后面会考虑更新一下。


好的，回复真迅速，谢谢大佬
