### ISSUE TITLE
internlm2_7b_chat必须要40G显存吗？

### ISSUE THREAD

**Issue by xxg98** [SmartFlowAI/EmoLLM#42]
只有3090ti，用Xtuner微调时，如何降低显存到24G以内：
![image](https://github.com/SmartFlowAI/EmoLLM/assets/98906194/42cac643-57c2-42f2-97c6-d95c37b4af38)

**Comment by aJupyter** [comment]
不用，可以开offload

**Comment by xxg98** [comment]
> 不用，可以开offload

可以详细指点一下吗？这个怎么开呢？

**Comment by aJupyter** [comment]
xtuner train xxx --deepspeed deepspeed_zero3_offload

**Comment by xxg98** [comment]
> xtuner train xxx --deepspeed deepspeed_zero3_offload


哇，谢谢大佬（星星眼）
有一个问题，文档用的是--deepspeed deepspeed_zero2，改成deepspeed_zero3没关系的吗？

**Comment by aJupyter** [comment]
没事的 支持1-3

**Comment by xxg98** [comment]
> 没事的 支持1-3


好嘞
