### ISSUE TITLE
修改license icon bug

### ISSUE THREAD

**Issue by aJupyter** [SmartFlowAI/EmoLLM#69]
@chg0901

**Comment by chg0901** [comment]
If we use the license template provided by the GitHub, 

We should not add additional text such as the red fonts parts

![image](https://github.com/SmartFlowAI/EmoLLM/assets/8240984/b9b9e8dd-0620-4327-82fd-b675466ccd8c)

**Comment by chg0901** [comment]
This issue is solved with the provided methods and could be closed now
